steps:

# deploy ingress image to GKE and create ingress
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - apply
  - --filename=defrr-ingress.yaml
  - --location=us-central1
  - --cluster=cluster-1