apiVersion: networking.k8s.io/v1
# uses backend.config.yaml
kind: Ingress
metadata:
  name: defrr-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    cloud.google.com/neg: '{"ingress": true}'
spec:
  rules:
  - host: defrr.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: web-map-http
            port:
              number: 80